USE WAREHOUSE CUSTOMER_REVENUE_WH;
USE DATABASE CUSTOMER_REVENUE_DB;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT CUSTOMER_REVENUE_CSV_FORMAT
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('', 'NULL', 'null')
    EMPTY_FIELD_AS_NULL = TRUE
    TRIM_SPACE = TRUE;

CREATE OR REPLACE STAGE CUSTOMER_REVENUE_STAGE
    FILE_FORMAT = CUSTOMER_REVENUE_CSV_FORMAT;

COPY INTO CUSTOMERS
FROM @CUSTOMER_REVENUE_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = CUSTOMER_REVENUE_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO ACCOUNT_OWNERS
FROM @CUSTOMER_REVENUE_STAGE/account_owners.csv
FILE_FORMAT = (FORMAT_NAME = CUSTOMER_REVENUE_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO PRODUCTS
FROM @CUSTOMER_REVENUE_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = CUSTOMER_REVENUE_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO SUBSCRIPTIONS
FROM @CUSTOMER_REVENUE_STAGE/subscriptions.csv
FILE_FORMAT = (FORMAT_NAME = CUSTOMER_REVENUE_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO TRANSACTIONS
FROM @CUSTOMER_REVENUE_STAGE/transactions.csv
FILE_FORMAT = (FORMAT_NAME = CUSTOMER_REVENUE_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO PRODUCT_USAGE
FROM @CUSTOMER_REVENUE_STAGE/product_usage.csv
FILE_FORMAT = (FORMAT_NAME = CUSTOMER_REVENUE_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO SUPPORT_TICKETS
FROM @CUSTOMER_REVENUE_STAGE/support_tickets.csv
FILE_FORMAT = (FORMAT_NAME = CUSTOMER_REVENUE_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO ACCOUNT_HEALTH
FROM @CUSTOMER_REVENUE_STAGE/account_health.csv
FILE_FORMAT = (FORMAT_NAME = CUSTOMER_REVENUE_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';
