version: 2

sources:
  - name: raw
    database: CUSTOMER_REVENUE_DB
    schema: RAW
    tables:
      - name: customers
      - name: account_owners
      - name: products
      - name: subscriptions
      - name: transactions
      - name: product_usage
      - name: support_tickets
      - name: account_health
